admin_example:
  resource: 'admin/example.yaml'
  prefix: /admin
  name_prefix: admin_example_
admin_auth:
  resource: 'admin/authentication.yaml'
  prefix: /
  name_prefix: admin_auth_
admin_home:
  resource: 'admin/homepage.yaml'
  prefix: /
  name_prefix: admin_home_
admin_space:
  resource: 'admin/space.yaml'
  prefix: /
  name_prefix: admin_space_
admin_agent:
  resource: 'admin/agent.yaml'
  prefix: /
  name_prefix: admin_agent_
admin_initiative:
  resource: 'admin/initiative.yaml'
  prefix: /
  name_prefix: admin_initiative_
admin_event:
  resource: 'admin/event.yaml'
  prefix: /
  name_prefix: admin_event_