openapi: 3.0.2
info:
  title: API Aurora
  description: |-
    API responsável por praticamente todas as funcionalidades de gerenciamento:
    - Agentes
    - Áreas de atividade
    - Espaços
    - Eventos
    - Faqs
    - Fases
    - Iniciativas
    - Oportunidades
    - Organizações
    - Selos
    - Tags
    - Usuários

    Links Importantes:
    - [Github](https://github.com/secultce/aurora)

  license:
    name: GPLv3
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /api
tags:
  - name: Autorização
    description: Endpoints relacionados a autorização
  - name: Agentes
    description: Endpoints relacionados aos agentes
  - name: Áreas de Atividade
    description: Endpoints relacionados às áreas de atividade
  - name: Espaços
    description: Endpoints relacionados aos espaços
  - name: Eventos
    description: Endpoints relacionados aos eventos
  - name: Iniciativas
    description: Endpoints relacionados às iniciativas
  - name: Inscrição na oportunidade
    description: Endpoints relacionados as inscrições na oportunidade
  - name: Inscrição na fase
    description: Endpoints relacionados as inscrições na fase
  - name: Faq
    description: Endpoints relacionados às faqs
  - name: Fases
    description: Endpoints relacionados às fases
  - name: Oportunidades
    description: Endpoints relacionados às oportunidades
  - name: Organizações
    description: Endpoints relacionados às organizações
  - name: Selos
    description: Endpoints relacionados aos selos
  - name: Tags
    description: Endpoints relacionados às tags
  - name: Usuários
    description: Endpoints relacionados aos usuários
paths:
  /activity-areas:
    $ref: './components/paths/activity-area/Collection.yaml'
  /activity-areas/{id}:
    $ref: './components/paths/activity-area/Item.yaml'
  /agents:
    $ref: './components/paths/agent/Collection.yaml'
  /agents/{id}:
    $ref: './components/paths/agent/Item.yaml'
  /agents/{id}/images:
    $ref: './components/paths/agent/UpdateImage.yaml'
  /events:
    $ref: './components/paths/event/Collection.yaml'
  /events/{id}:
    $ref: './components/paths/event/Item.yaml'
  /events/{id}/images:
    $ref: './components/paths/event/UpdateImage.yaml'
  /faqs:
    $ref: './components/paths/faq/Collection.yaml'
  /faqs/{id}:
    $ref: './components/paths/faq/Item.yaml'
  /initiatives:
    $ref: './components/paths/initiative/Collection.yaml'
  /initiatives/{id}:
    $ref: './components/paths/initiative/Item.yaml'
  /initiatives/{id}/images:
    $ref: './components/paths/initiative/UpdateImage.yaml'
  /login:
    $ref: './components/paths/login/Item.yaml'
  /logout:
    $ref: './components/paths/logout/Item.yaml'
  /opportunities:
    $ref: './components/paths/opportunity/Collection.yaml'
  /opportunities/{id}:
    $ref: './components/paths/opportunity/Item.yaml'
  /opportunities/{id}/images:
    $ref: './components/paths/opportunity/UpdateImage.yaml'
  /opportunities/{opportunity}/inscriptions:
    $ref: './components/paths/inscription-opportunity/Collection.yaml'
  /opportunities/{opportunity}/inscriptions/{id}:
    $ref: './components/paths/inscription-opportunity/Item.yaml'
  /opportunities/{opportunity}/phases:
    $ref: './components/paths/phase/Collection.yaml'
  /opportunities/{opportunity}/phases/{id}:
    $ref: './components/paths/phase/Item.yaml'
  /opportunities/{opportunity}/phases/{phase}/inscriptions:
    $ref: './components/paths/inscription-phase/Collection.yaml'
  /organizations:
    $ref: './components/paths/organization/Collection.yaml'
  /organizations/{id}:
    $ref: './components/paths/organization/Item.yaml'
  /organizations/{id}/images:
    $ref: './components/paths/organization/UpdateImage.yaml'
  /seals:
    $ref: './components/paths/seal/Collection.yaml'
  /seals/{id}:
    $ref: './components/paths/seal/Item.yaml'
  /spaces:
    $ref: './components/paths/space/Collection.yaml'
  /spaces/{id}:
    $ref: './components/paths/space/Item.yaml'
  /spaces/{id}/images:
    $ref: './components/paths/space/UpdateImage.yaml'
  /tags:
    $ref: './components/paths/tag/Collection.yaml'
  /tags/{id}:
    $ref: './components/paths/tag/Item.yaml'
  /users:
    $ref: './components/paths/user/Collection.yaml'
  /users/{id}:
    $ref: './components/paths/user/Item.yaml'
components:
  schemas:
    ActivityArea:
      $ref: './components/schemas/activity-area.yaml'
    Agent:
      $ref: './components/schemas/agent.yaml'
    Event:
      $ref: './components/schemas/event.yaml'
    Faq:
      $ref: './components/schemas/faq.yaml'
    Initiative:
      $ref: './components/schemas/initiative.yaml'
    InscriptionOpportunity:
      $ref: './components/schemas/inscription-opportunity.yaml'
    InscriptionPhase:
      $ref: './components/schemas/inscription-phase.yaml'
    Opportunity:
      $ref: './components/schemas/opportunity.yaml'
    Organization:
      $ref: './components/schemas/organization.yaml'
    Phase:
      $ref: './components/schemas/phase.yaml'
    Seal:
      $ref: './components/schemas/seal.yaml'
    Space:
      $ref: './components/schemas/space.yaml'
    Tag:
      $ref: './components/schemas/tag.yaml'
    User:
      $ref: './components/schemas/user.yaml'
