list:
  path: /
  controller: App\Controller\Web\Admin\EventAdminController::list
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\EventAdminController::remove
  methods: ['GET']

create:
  path: /adicionar
  controller: App\Controller\Web\Admin\EventAdminController::create
  methods: ['GET', 'POST']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\EventAdminController::timeline
  methods: ['GET']

edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\EventAdminController::edit
  methods: ['GET', 'POST']
