create:
  path: /adicionar
  controller: App\Controller\Web\Admin\InitiativeAdminController::create
  methods: ['GET']

store:
  path: /store
  controller: App\Controller\Web\Admin\InitiativeAdminController::store
  methods: ['POST']

list:
  path: /
  controller: App\Controller\Web\Admin\InitiativeAdminController::list
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\InitiativeAdminController::remove
  methods: ['GET']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\InitiativeAdminController::timeline
  methods: ['GET']

edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\InitiativeAdminController::edit
  methods: ['GET', 'POST']
