create:
  path: /adicionar
  controller: App\Controller\Web\Admin\OpportunityAdminController::create
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Web\Admin\OpportunityAdminController::list
  methods: ['GET']

edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\OpportunityAdminController::edit
  methods: ['GET', 'POST']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\OpportunityAdminController::remove
  methods: ['GET']

store:
  path: /store
  controller: App\Controller\Web\Admin\OpportunityAdminController::store
  methods: ['POST']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\OpportunityAdminController::timeline
  methods: ['GET']

get:
  path: /{id}
  controller: App\Controller\Web\Admin\OpportunityAdminController::get
  methods: ['GET']

subscribe:
  path: /{id}/subscribe
  controller: App\Controller\Web\Admin\OpportunityAdminController::subscribe
  methods: ['GET']

phase_timeline:
  path: /{id}/phases/{phaseId}/timeline
  controller: App\Controller\Web\Admin\OpportunityAdminController::phaseTimeline
  methods: ['GET']
